namespace: pyler-mlops

pvc:
  name: pyler-model-pvc

model:
  name: resnet
  repositoryPath: /models
  config: |
    name: "resnet"
    platform: "pytorch_libtorch"
    max_batch_size: 10
    input [
      {
        name: "INPUT__0"
        data_type: TYPE_FP32
        format: FORMAT_NCHW
        dims: [1, 224, 224]
      }
    ]
    output [
      {
        name: "OUTPUT__0"
        data_type: TYPE_FP32
        dims: [10]
      }
    ]

image:
  triton: nvcr.io/nvidia/tritonserver:24.03-py3

triton:
  prepareJobName: job-prepare-model
  exitOnError: false