apiVersion: apps/v1
kind: Deployment
metadata:
  name: triton-server
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: triton
  template:
    metadata:
      labels:
        app: triton
    spec:
      containers:
        - name: triton
          image: {{ .Values.image.triton }}
          args:
            - "tritonserver"
            - "--model-repository={{ .Values.modelResnet.repositoryPath }}"
            - "--exit-on-error={{ .Values.triton.exitOnError }}"
            - "--model-control-mode=poll"
          ports:
            - containerPort: 8001
          volumeMounts:
            - name: model-base
              mountPath: {{ .Values.modelResnet.repositoryPath }}
      volumes:
        - name: model-base
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: triton-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: triton
  type: NodePort
  ports:
    - name: grpc
      port: 8001
      targetPort: 8001
      nodePort: 30001
