apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.triton.prepareJobName }}
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: prepare-model
          image: busybox
          command:
            - sh
            - -c
            - |
              mkdir -p {{ .Values.modelResnet.repositoryPath }}/{{ .Values.modelResnet.name }}/{{ .Values.modelResnet.version }} && \
              mv {{ .Values.modelResnet.repositoryPath }}/{{ .Values.modelResnet.name }}/model.pt {{ .Values.modelResnet.repositoryPath }}/{{ .Values.modelResnet.name }}/{{ .Values.modelResnet.version }}/model.pt &&
              echo "$CONFIG_PBTXT" > {{ .Values.modelResnet.repositoryPath }}/{{ .Values.modelResnet.name }}/config.pbtxt
          env:
            - name: CONFIG_PBTXT
              valueFrom:
                configMapKeyRef:
                  name: resnet-config
                  key: config.pbtxt
          volumeMounts:
            - name: model-base
              mountPath: {{ .Values.modelResnet.repositoryPath }}
      volumes:
        - name: model-base
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.name }}
