apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.triton.prepareJobName }}
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: prepare
          image: busybox
          command:
            - sh
            - -c
            - |
              mkdir -p /models/{{ .Values.model.name }}/1 && \
              mv /models/{{ .Values.model.name }}/model.pt /models/{{ .Values.model.name }}/1/model.pt && \
              echo "$CONFIG_PBTXT" > /models/{{ .Values.model.name }}/config.pbtxt
          env:
            - name: CONFIG_PBTXT
              valueFrom:
                configMapKeyRef:
                  name: triton-config
                  key: config.pbtxt
          volumeMounts:
            - name: model-base
              mountPath: /models
      volumes:
        - name: model-base
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.name }}
